/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosantiago.pkg1;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

/**
 *

 */
public class Menu extends javax.swing.JFrame {

    static Grafo g;
    static String archivo;

    /**
     * Creates new form Menu
     */
    public Menu(Grafo grafo, String a) {
        initComponents();
        this.setVisible(true);
        g = grafo;
        archivo = a;
    }

    public void escribirArchivo() {
        String path = archivo;
        File file = new File(path);
        file.delete();
        try {
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            PrintWriter pw = new PrintWriter(fw);
            pw.write("ciudad" + "\n");
            for (int i = 0; i < g.getMax_ciudades(); i++) {
                try {
                    pw.write(g.getVertices_ciudades()[i].getpFirst().getTitulo() + "\n");

                } catch (Exception e) {
                    System.out.println("En " + i + " no hay usuario registrado");
                }
            }
            pw.write("aristas");
            for (int i = 0; i < g.getMax_ciudades(); i++) {
                if (g.getVertices_ciudades()[i].getpFirst() != null) {
                    NodoCiudad ciudad = g.getVertices_ciudades()[i].getpFirst();
                    while (ciudad.getpNext() != null) {
                        pw.write("\n" + g.getVertices_ciudades()[i].getpFirst().getTitulo() + "," + ciudad.getpNext().getTitulo() + "," + ciudad.getpNext().getDistancia());
                        ciudad = ciudad.getpNext();
                    }
                }
            }
            pw.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hormigas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        insertar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sim = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        ciudad2 = new javax.swing.JTextField();
        distancia = new javax.swing.JTextField();
        ciudad1 = new javax.swing.JTextField();
        origen = new javax.swing.JTextField();
        destino = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ciclos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        imprimir = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Hormigas:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, -1, 30));

        hormigas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(hormigas, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 110, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel2.setText("Ant System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton4.setText("Simular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 640, -1, -1));

        insertar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 250, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Ciudades y sus caminos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 30));

        sim.setColumns(20);
        sim.setRows(5);
        jScrollPane1.setViewportView(sim);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 430, 460));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Ingrese la ciudad:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        ciudad2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(ciudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 80, 30));

        distancia.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 80, 30));

        ciudad1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(ciudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 80, 30));

        origen.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 110, 30));

        destino.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 110, 30));

        a.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 80, 30));

        b.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 80, 30));

        p.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 80, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Añade la ciudad y la distancia entre ellas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Ciudad Origen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Ciudad Destino");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("α");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setText("β");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("ρ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, -1, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("Ciclos:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, -1, 30));

        ciclos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(ciclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 80, 30));

        imprimir.setColumns(20);
        imprimir.setRows(5);
        jScrollPane2.setViewportView(imprimir);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 400, 350));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setText("Resultados de la simulacion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, -1, 30));

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton6.setText("Ver Grafo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            g.crear_Camino(this.ciudad1.getText(), this.ciudad2.getText(), Integer.parseInt(this.distancia.getText()));
            this.ciudad1.setText("");
            this.ciudad2.setText("");
            this.distancia.setText("");

            this.imprimir.setText(g.imprimir());
            if (!archivo.equals("")) {
                escribirArchivo();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "INTRODUZCA VALORES VALIDOS");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(g.buscar(this.insertar.getText())== null){
            g.añadir_Ciudad(this.insertar.getText());
            System.out.println(this.insertar.getText());
            this.insertar.setText("");
            this.imprimir.setText(g.imprimir());
            if (!archivo.equals("")) {
                escribirArchivo();
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "LA CIUDAD YA EXISTE");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        g.eliminar_Ciudad(this.insertar.getText());
        this.insertar.setText("");
        this.imprimir.setText(g.imprimir());
        if (!archivo.equals("")) {
            escribirArchivo();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            double p1 = Double.parseDouble(this.p.getText());
            if (p1 < 0 || p1 >= 1) {
                JOptionPane.showMessageDialog(rootPane, "P debe ser un valor entre 0 y 1");
            } else {
                try {
                    if (g.getCiudades_actuales() >= 4) {
                        g.definirPrimero(this.origen.getText());
                        g.definirUltimo(this.destino.getText());
                        g.iniciarFeromonas();
                        for (int j = 0; j < Integer.parseInt(this.ciclos.getText()); j++) {
                            for (int i = 0; i < Integer.parseInt(this.hormigas.getText()); i++) {
                                Hormiga h = new Hormiga();
                                g.recorrer(h, Double.parseDouble(this.a.getText()), Double.parseDouble(this.b.getText()));
                                this.sim.setText(this.sim.getText() + "Recorrido de la hormiga: " + h.visitados + ". Distancia del recorrido: " + h.recorrido + "\n");
                            }
                            this.sim.setText(this.sim.getText() + g.actualizarPi(Double.parseDouble(this.p.getText())) + "\n-------------------------------------------------------\n");
                        }
                        this.sim.setText("El camino más óptimo es: " + g.menor.visitados + " con una distancia total de " + g.menor.recorrido + "\n-------------------------------------------------------\n" + this.sim.getText());
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "DEBE TENER AL MENOS 4 CIUDADES PARA SIMULAR");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "INTRODUZCA VALORES VALIDOS");
                }

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "INTRODUZCA VALORES VALIDOS");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Graph graph = new SingleGraph("MyGraph");
        graph.setAttribute("ui.stylesheet", "node { shape: circle; fill-color: #5DC1B9; text-color: #000000; size: 40px; } "
                + " edge { size: 2px; shape: line; fill-color: #D3D3D3; }");
        for (int i = 0; i < g.getMax_ciudades(); i++) {
            if (g.getVertices_ciudades()[i].getpFirst() != null) {
                String username = g.getVertices_ciudades()[i].getpFirst().getTitulo();
                Node user = graph.addNode(username);
                user.setAttribute("ui.label", username);
            }
        }

        for (int i = 0; i < g.getMax_ciudades(); i++) {
            if (g.getVertices_ciudades()[i].getpFirst() != null) {
                String source = g.getVertices_ciudades()[i].getpFirst().getTitulo();
                NodoCiudad currentUser = g.getVertices_ciudades()[i].getpFirst().getpNext();
                while (currentUser != null) {
                    String target = currentUser.getTitulo();
                    try {
                        Edge edge = graph.addEdge(source + "-" + target, source, target, false);

                        edge.setAttribute("ui.style", "fill-color: black;");
                        currentUser = currentUser.getpNext();
                    } catch (Exception e) {
                        currentUser = currentUser.getpNext();
                    }
                }
            }
        }
        System.setProperty("org.graphstream.ui", "org.graphstream.ui.swing");
        Viewer viewer = graph.display();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(g, archivo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField ciclos;
    private javax.swing.JTextField ciudad1;
    private javax.swing.JTextField ciudad2;
    private javax.swing.JTextField destino;
    private javax.swing.JTextField distancia;
    private javax.swing.JTextField hormigas;
    private javax.swing.JTextArea imprimir;
    private javax.swing.JTextField insertar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField origen;
    private javax.swing.JTextField p;
    private javax.swing.JTextArea sim;
    // End of variables declaration//GEN-END:variables
}
